#!url=https://whatshub.top/module/picsart.module

#!name=Picsart-VN-Creative

#!desc=picart pro không quảng cáo

#!author=Creative

#!version=1.0.0

[Script]

Picsart=type=http-response,pattern=https:\/\/api\.(picsart|meiease)\.c(n|om)\/users\/show\/me\.json,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/vngctcreative/module_ios/main/java/picsart.js

[MITM]

hostname = %APPEND% api.picsart.c*, api.meiease.c*
