#!url=https://whatshub.top/module/soundcloud.module

#!name=SoundCloud-VN-Creative

#!desc=SoundCloud không quảng cáo

#!version=1.0.0

[Script]

SoundCloudGo+=type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://raw.githubusercontent.com/vngctcreative/module_ios/main/java/soundcloud.js

[MITM]

hostname= %APPEND% api-mobile.soundcloud.com
