#!url=https://whatshub.top/module/spotify_lyric.module

#!name=Spotify-VN-Creative

#!desc=Spotify Pro không quảng cáo

[Script]

spotify歌词翻译 = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/color-lyrics\/v2\/track\/,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/vngctcreative/module_ios/main/java/spotify.js,argument=appid=此处填入APPID&securityKey=此处填入密钥

[MITM]

hostname = %APPEND% spclient.wg.spotify.com
